version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
environment:
  STACK_NAME: SampleStack
jobs:
  execute-cloud-formation:
    environment:
      STACK_NAME: SampleStack
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run: aws cloudformation describe-stacks --stack-name $STACK_NAME
      - run: |
          if [ $? -eq 0 ]; then
            aws cloudformation delete-stack --stack-name $STACK_NAME
          else
            aws cloudformation create-stack --stack-name $STACK_NAME --template-body file://service/sample.yml
            aws cloudformation wait stack-create-complete --stack-name $STACK_NAME
          fi
workflows:
  build:
    jobs:
      - execute-cloud-formation:
          context: aws
