version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
environment:
  STACK_NAME: SampleStack
jobs:
  execute-cloud-formation:
    environment:
      STACK_NAME: SampleStack
      RESULT_FILE: command_result
      TEMPLATE_FILE: file://service/sample.yml
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run: set +e
      - run: aws cloudformation describe-stacks --stack-name SampleStack 2>/dev/null > $RESULT_FILE
      - run:
          name: Create or Update
          command: |
            if [ ! -s $RESULT_FILE ]; then
              aws cloudformation create-stack --stack-name $STACK_NAME --template-body $TEMPLATE_FILE
              aws cloudformation wait stack-create-complete --stack-name $STACK_NAME
            else
              aws cloudformation update-stack --stack-name $STACK_NAME --template-body $TEMPLATE_FILE --no-fail-on-empty-changeset
              aws cloudformation wait stack-update-complete --stack-name $STACK_NAME
            fi
          when: always
      - run: set -e
workflows:
  build:
    jobs:
      - execute-cloud-formation:
          context: aws
